spring:
  profiles:
    active: dev
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: walletdbuser
    password: walletdbpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
app:
  jwt:
    secret: ZwHb76tYhO6UCtde6fdjaMkYS5SeLfruZ0LOB6WyOuY=
    expiration: 86400000

server:
  port: 8080